# Generated by Django 4.1.1 on 2022-12-13 20:42

import apps.barberos.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.TimeField(help_text='La hora debe estar en este formato: 14:00 o 14:00:00')),
                ('hasta', models.TimeField(help_text='La hora debe estar en este formato: 15:30 o 15:30:00')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('precio', models.IntegerField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Barbero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rut', models.CharField(help_text='Ingrese un rut valido. Ej: 22755865-K', max_length=15, validators=[apps.barberos.models.validarRut], verbose_name='RUT')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='El número debe estar en este formato: 933789228', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbero', to='barberos.servicio')),
            ],
            options={
                'unique_together': {('rut', 'servicio')},
            },
        ),
    ]
