# Generated by Django 4.1.1 on 2022-12-13 20:42

import apps.cuentas.models
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(help_text='Un nombre corto que será usado para identificarlo de forma única en la plataforma.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Ingrese un nombre de usuario valido. Este valor debe contener solo letras, números y los caracteres: @/./+/-/_.', 'invalid')], verbose_name='Usuario')),
                ('first_name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('sexo', models.CharField(choices=[('MAS', 'Masculino'), ('FEM', 'Femenino')], max_length=9)),
                ('telefono', models.CharField(help_text='El número debe estar en este formato: 933789228', max_length=9, validators=[django.core.validators.RegexValidator(message='El número debe estar en este formato: 933789228.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefono')),
                ('rut', models.CharField(help_text='Ingrese un rut valido. Ej: 22755865-K', max_length=10, unique=True, validators=[apps.cuentas.models.validarRut], verbose_name='RUT')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
